// Auto-generated from /usr/share/zoneinfo/iso3166.tab using Intl.DisplayNames(it)
export type CountryOption = { code: string; label: string };
export const COUNTRIES: CountryOption[] = [
  { code: 'AF', label: 'Afghanistan' },
  { code: 'AL', label: 'Albania' },
  { code: 'DZ', label: 'Algeria' },
  { code: 'AD', label: 'Andorra' },
  { code: 'AO', label: 'Angola' },
  { code: 'AI', label: 'Anguilla' },
  { code: 'AQ', label: 'Antartide' },
  { code: 'AG', label: 'Antigua e Barbuda' },
  { code: 'SA', label: 'Arabia Saudita' },
  { code: 'AR', label: 'Argentina' },
  { code: 'AM', label: 'Armenia' },
  { code: 'AW', label: 'Aruba' },
  { code: 'AU', label: 'Australia' },
  { code: 'AT', label: 'Austria' },
  { code: 'AZ', label: 'Azerbaigian' },
  { code: 'BS', label: 'Bahamas' },
  { code: 'BH', label: 'Bahrein' },
  { code: 'BD', label: 'Bangladesh' },
  { code: 'BB', label: 'Barbados' },
  { code: 'BE', label: 'Belgio' },
  { code: 'BZ', label: 'Belize' },
  { code: 'BJ', label: 'Benin' },
  { code: 'BM', label: 'Bermuda' },
  { code: 'BT', label: 'Bhutan' },
  { code: 'BY', label: 'Bielorussia' },
  { code: 'BO', label: 'Bolivia' },
  { code: 'BA', label: 'Bosnia ed Erzegovina' },
  { code: 'BW', label: 'Botswana' },
  { code: 'BR', label: 'Brasile' },
  { code: 'BN', label: 'Brunei' },
  { code: 'BG', label: 'Bulgaria' },
  { code: 'BF', label: 'Burkina Faso' },
  { code: 'BI', label: 'Burundi' },
  { code: 'KH', label: 'Cambogia' },
  { code: 'CM', label: 'Camerun' },
  { code: 'CA', label: 'Canada' },
  { code: 'CV', label: 'Capo Verde' },
  { code: 'BQ', label: 'Caraibi Olandesi' },
  { code: 'CZ', label: 'Cechia' },
  { code: 'TD', label: 'Ciad' },
  { code: 'CL', label: 'Cile' },
  { code: 'CN', label: 'Cina' },
  { code: 'CY', label: 'Cipro' },
  { code: 'VA', label: 'Città del Vaticano' },
  { code: 'CO', label: 'Colombia' },
  { code: 'KM', label: 'Comore' },
  { code: 'CD', label: 'Congo - Kinshasa' },
  { code: 'CG', label: 'Congo-Brazzaville' },
  { code: 'KP', label: 'Corea del Nord' },
  { code: 'KR', label: 'Corea del Sud' },
  { code: 'CI', label: 'Costa d’Avorio' },
  { code: 'CR', label: 'Costa Rica' },
  { code: 'HR', label: 'Croazia' },
  { code: 'CU', label: 'Cuba' },
  { code: 'CW', label: 'Curaçao' },
  { code: 'DK', label: 'Danimarca' },
  { code: 'DM', label: 'Dominica' },
  { code: 'EC', label: 'Ecuador' },
  { code: 'EG', label: 'Egitto' },
  { code: 'SV', label: 'El Salvador' },
  { code: 'AE', label: 'Emirati Arabi Uniti' },
  { code: 'ER', label: 'Eritrea' },
  { code: 'EE', label: 'Estonia' },
  { code: 'SZ', label: 'Eswatini' },
  { code: 'ET', label: 'Etiopia' },
  { code: 'FJ', label: 'Figi' },
  { code: 'PH', label: 'Filippine' },
  { code: 'FI', label: 'Finlandia' },
  { code: 'FR', label: 'Francia' },
  { code: 'GA', label: 'Gabon' },
  { code: 'GM', label: 'Gambia' },
  { code: 'GE', label: 'Georgia' },
  { code: 'GS', label: 'Georgia del Sud e Sandwich Australi' },
  { code: 'DE', label: 'Germania' },
  { code: 'GH', label: 'Ghana' },
  { code: 'JM', label: 'Giamaica' },
  { code: 'JP', label: 'Giappone' },
  { code: 'GI', label: 'Gibilterra' },
  { code: 'DJ', label: 'Gibuti' },
  { code: 'JO', label: 'Giordania' },
  { code: 'GR', label: 'Grecia' },
  { code: 'GD', label: 'Grenada' },
  { code: 'GL', label: 'Groenlandia' },
  { code: 'GP', label: 'Guadalupa' },
  { code: 'GU', label: 'Guam' },
  { code: 'GT', label: 'Guatemala' },
  { code: 'GG', label: 'Guernsey' },
  { code: 'GN', label: 'Guinea' },
  { code: 'GQ', label: 'Guinea Equatoriale' },
  { code: 'GW', label: 'Guinea-Bissau' },
  { code: 'GY', label: 'Guyana' },
  { code: 'GF', label: 'Guyana Francese' },
  { code: 'HT', label: 'Haiti' },
  { code: 'HN', label: 'Honduras' },
  { code: 'IN', label: 'India' },
  { code: 'ID', label: 'Indonesia' },
  { code: 'IR', label: 'Iran' },
  { code: 'IQ', label: 'Iraq' },
  { code: 'IE', label: 'Irlanda' },
  { code: 'IS', label: 'Islanda' },
  { code: 'BV', label: 'Isola Bouvet' },
  { code: 'CX', label: 'Isola Christmas' },
  { code: 'IM', label: 'Isola di Man' },
  { code: 'NF', label: 'Isola Norfolk' },
  { code: 'AX', label: 'Isole Åland' },
  { code: 'KY', label: 'Isole Cayman' },
  { code: 'CC', label: 'Isole Cocos (Keeling)' },
  { code: 'CK', label: 'Isole Cook' },
  { code: 'FO', label: 'Isole Fær Øer' },
  { code: 'FK', label: 'Isole Falkland' },
  { code: 'HM', label: 'Isole Heard e McDonald' },
  { code: 'MP', label: 'Isole Marianne Settentrionali' },
  { code: 'MH', label: 'Isole Marshall' },
  { code: 'UM', label: 'Isole Minori Esterne degli Stati Uniti' },
  { code: 'PN', label: 'Isole Pitcairn' },
  { code: 'SB', label: 'Isole Salomone' },
  { code: 'TC', label: 'Isole Turks e Caicos' },
  { code: 'VI', label: 'Isole Vergini Americane' },
  { code: 'VG', label: 'Isole Vergini Britanniche' },
  { code: 'IL', label: 'Israele' },
  { code: 'IT', label: 'Italia' },
  { code: 'JE', label: 'Jersey' },
  { code: 'KZ', label: 'Kazakistan' },
  { code: 'KE', label: 'Kenya' },
  { code: 'KG', label: 'Kirghizistan' },
  { code: 'KI', label: 'Kiribati' },
  { code: 'KW', label: 'Kuwait' },
  { code: 'LA', label: 'Laos' },
  { code: 'LS', label: 'Lesotho' },
  { code: 'LV', label: 'Lettonia' },
  { code: 'LB', label: 'Libano' },
  { code: 'LR', label: 'Liberia' },
  { code: 'LY', label: 'Libia' },
  { code: 'LI', label: 'Liechtenstein' },
  { code: 'LT', label: 'Lituania' },
  { code: 'LU', label: 'Lussemburgo' },
  { code: 'MK', label: 'Macedonia del Nord' },
  { code: 'MG', label: 'Madagascar' },
  { code: 'MW', label: 'Malawi' },
  { code: 'MY', label: 'Malaysia' },
  { code: 'MV', label: 'Maldive' },
  { code: 'ML', label: 'Mali' },
  { code: 'MT', label: 'Malta' },
  { code: 'MA', label: 'Marocco' },
  { code: 'MQ', label: 'Martinica' },
  { code: 'MR', label: 'Mauritania' },
  { code: 'MU', label: 'Mauritius' },
  { code: 'YT', label: 'Mayotte' },
  { code: 'MX', label: 'Messico' },
  { code: 'FM', label: 'Micronesia' },
  { code: 'MD', label: 'Moldavia' },
  { code: 'MC', label: 'Monaco' },
  { code: 'MN', label: 'Mongolia' },
  { code: 'ME', label: 'Montenegro' },
  { code: 'MS', label: 'Montserrat' },
  { code: 'MZ', label: 'Mozambico' },
  { code: 'MM', label: 'Myanmar (Birmania)' },
  { code: 'NA', label: 'Namibia' },
  { code: 'NR', label: 'Nauru' },
  { code: 'NP', label: 'Nepal' },
  { code: 'NI', label: 'Nicaragua' },
  { code: 'NE', label: 'Niger' },
  { code: 'NG', label: 'Nigeria' },
  { code: 'NU', label: 'Niue' },
  { code: 'NO', label: 'Norvegia' },
  { code: 'NC', label: 'Nuova Caledonia' },
  { code: 'NZ', label: 'Nuova Zelanda' },
  { code: 'OM', label: 'Oman' },
  { code: 'NL', label: 'Paesi Bassi' },
  { code: 'PK', label: 'Pakistan' },
  { code: 'PW', label: 'Palau' },
  { code: 'PA', label: 'Panama' },
  { code: 'PG', label: 'Papua Nuova Guinea' },
  { code: 'PY', label: 'Paraguay' },
  { code: 'PE', label: 'Perù' },
  { code: 'PF', label: 'Polinesia Francese' },
  { code: 'PL', label: 'Polonia' },
  { code: 'PT', label: 'Portogallo' },
  { code: 'PR', label: 'Portorico' },
  { code: 'QA', label: 'Qatar' },
  { code: 'HK', label: 'RAS di Hong Kong' },
  { code: 'MO', label: 'RAS di Macao' },
  { code: 'GB', label: 'Regno Unito' },
  { code: 'CF', label: 'Repubblica Centrafricana' },
  { code: 'DO', label: 'Repubblica Dominicana' },
  { code: 'RE', label: 'Riunione' },
  { code: 'RO', label: 'Romania' },
  { code: 'RW', label: 'Ruanda' },
  { code: 'RU', label: 'Russia' },
  { code: 'EH', label: 'Sahara Occidentale' },
  { code: 'KN', label: 'Saint Kitts e Nevis' },
  { code: 'LC', label: 'Saint Lucia' },
  { code: 'MF', label: 'Saint Martin' },
  { code: 'VC', label: 'Saint Vincent e Grenadine' },
  { code: 'BL', label: 'Saint-Barthélemy' },
  { code: 'PM', label: 'Saint-Pierre e Miquelon' },
  { code: 'WS', label: 'Samoa' },
  { code: 'AS', label: 'Samoa Americane' },
  { code: 'SM', label: 'San Marino' },
  { code: 'SH', label: 'Sant’Elena' },
  { code: 'ST', label: 'São Tomé e Príncipe' },
  { code: 'SN', label: 'Senegal' },
  { code: 'RS', label: 'Serbia' },
  { code: 'SC', label: 'Seychelles' },
  { code: 'SL', label: 'Sierra Leone' },
  { code: 'SG', label: 'Singapore' },
  { code: 'SX', label: 'Sint Maarten' },
  { code: 'SY', label: 'Siria' },
  { code: 'SK', label: 'Slovacchia' },
  { code: 'SI', label: 'Slovenia' },
  { code: 'SO', label: 'Somalia' },
  { code: 'ES', label: 'Spagna' },
  { code: 'LK', label: 'Sri Lanka' },
  { code: 'US', label: 'Stati Uniti' },
  { code: 'SS', label: 'Sud Sudan' },
  { code: 'ZA', label: 'Sudafrica' },
  { code: 'SD', label: 'Sudan' },
  { code: 'SR', label: 'Suriname' },
  { code: 'SJ', label: 'Svalbard e Jan Mayen' },
  { code: 'SE', label: 'Svezia' },
  { code: 'CH', label: 'Svizzera' },
  { code: 'TJ', label: 'Tagikistan' },
  { code: 'TW', label: 'Taiwan' },
  { code: 'TZ', label: 'Tanzania' },
  { code: 'TF', label: 'Terre Australi Francesi' },
  { code: 'PS', label: 'Territori Palestinesi' },
  { code: 'IO', label: 'Territorio Britannico dell’Oceano Indiano' },
  { code: 'TH', label: 'Thailandia' },
  { code: 'TL', label: 'Timor Est' },
  { code: 'TG', label: 'Togo' },
  { code: 'TK', label: 'Tokelau' },
  { code: 'TO', label: 'Tonga' },
  { code: 'TT', label: 'Trinidad e Tobago' },
  { code: 'TN', label: 'Tunisia' },
  { code: 'TR', label: 'Turchia' },
  { code: 'TM', label: 'Turkmenistan' },
  { code: 'TV', label: 'Tuvalu' },
  { code: 'UA', label: 'Ucraina' },
  { code: 'UG', label: 'Uganda' },
  { code: 'HU', label: 'Ungheria' },
  { code: 'UY', label: 'Uruguay' },
  { code: 'UZ', label: 'Uzbekistan' },
  { code: 'VU', label: 'Vanuatu' },
  { code: 'VE', label: 'Venezuela' },
  { code: 'VN', label: 'Vietnam' },
  { code: 'WF', label: 'Wallis e Futuna' },
  { code: 'YE', label: 'Yemen' },
  { code: 'ZM', label: 'Zambia' },
  { code: 'ZW', label: 'Zimbabwe' },
  { code: 'OTHER', label: 'Altro…' },
];

export const WORLD_COUNTRY_OPTIONS: Array<{ code: string; name: string }> = COUNTRIES.map((c) => ({
  code: c.code,
  name: c.label,
}));

const COUNTRY_NAME_MAP = new Map<string, string>(COUNTRIES.map((c) => [c.code.toUpperCase(), c.label]));
const EU_CODE_SET = new Set([
  'AT','BE','BG','HR','CY','CZ','DK','EE','FI','FR','DE','GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','RO','SK','SI','ES','SE',
]);

export function getCountryName(code?: string | null): string | null {
  if (!code) return null;
  const key = code.trim().toUpperCase();
  return COUNTRY_NAME_MAP.get(key) ?? null;
}

export function isEuCountry(code: string): boolean {
  if (!code) return false;
  return EU_CODE_SET.has(code.trim().toUpperCase());
}

export const COUNTRY_OPTIONS: Array<{ label: string; value: string }> = [
  { label: 'Tutti i paesi', value: '' },
  ...WORLD_COUNTRY_OPTIONS.map((option) => ({ label: option.name, value: option.code })),
];
