export const PROFILE_PATCH_FIELDS = [
  "full_name",
  "display_name",
  "avatar_url",
  "bio",
  "country",
  "region",
  "province",
  "birth_year",
  "birth_place",
  "city",
  "residence_region_id",
  "residence_province_id",
  "residence_municipality_id",
  "birth_country",
  "birth_region_id",
  "birth_province_id",
  "birth_municipality_id",
  "foot",
  "height_cm",
  "weight_kg",
  "sport",
  "role",
  "visibility",
  "interest_country",
  "interest_region_id",
  "interest_province_id",
  "interest_municipality_id",
  "interest_region",
  "interest_province",
  "interest_city",
  "links",
  "skills",
  "notify_email_new_message",
  "account_type",
  "club_foundation_year",
  "club_stadium",
  "club_stadium_address",
  "club_stadium_lat",
  "club_stadium_lng",
  "club_league_category",
  "club_motto",
] as const;

export type ProfilePatchField = (typeof PROFILE_PATCH_FIELDS)[number];
